### PR TITLE
Faster Grounding

### PR DESCRIPTION
**Pull request by wmcclinton**
This PR improves grounding, by only re-grounding atoms whose objects experience state changes during the transitions.

### CODE REVIEW

**Review by NishanthJKumar — APPROVED** [review]
Beautiful, LGTM! Thanks for the quick work on this.

One question, did you somehow test that the atoms before and after this change are the same?

**Comment by wmcclinton** [comment]
> Beautiful, LGTM! Thanks for the quick work on this.
> 
> One question, did you somehow test that the atoms before and after this change are the same?

No, I am now

**Comment by wmcclinton** [comment]
> Beautiful, LGTM! Thanks for the quick work on this.
> 
> One question, did you somehow test that the atoms before and after this change are the same?

Confirmed it works!

**Review by NishanthJKumar — APPROVED** [review]
very minor feedback on fixing a comment to make it clearer

**Pull request merged**
